[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = {path ="../entity"}

serde = { version = "1.0.204", features = ["derive"] }
async-graphql = "7.0.6"
chrono = "0.4.38"
xlsxwriter = "0.6.1"
nanoid = "0.4.0"

